# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0c4c53rjpcavsdsq8w8gy665jsin7rxjz9238pqx3ba6ck0ivys4";
    aarch64-linux = "0qr9vzdwnxw36q0pp8mf2inzngwij9szblxc89p9rbrsnnc1dcck";
    x86_64-darwin = "1w7zfv1hqlh0ip440cnrmjcmwky73l2parzxsqf5ak45pykkc8zq";
    aarch64-darwin = "1ac6vppb6g43hjj656gb5i564h1yjhm75xcgn0bqby9pp8w9xqgs";
  };

  urlMap = {
    x86_64-linux = "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "ytt-ext";
  version = "0.48.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ${lib.nameFromURL urlMap.${system} "."} $out/bin/ytt
  '';

  system = system;

  meta = {

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
