# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YttExt < Formula
  desc ""
  homepage ""
  version "0.47.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.47.0/ytt-darwin-amd64"
      sha256 "fab7b511b9325dbf682bd768274e2870bf1ebee86721d788256e301aed432f89"

      def install
        bin.install stable.url.split("/")[-1] => "ytt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.47.0/ytt-darwin-arm64"
      sha256 "5fdfdd3732f960408ff1e4dd5fd06c1fa4dafbb61fad3a78ded2ff7ed70538bd"

      def install
        bin.install stable.url.split("/")[-1] => "ytt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.47.0/ytt-linux-amd64"
      sha256 "29caad093abb35ff4ddc26ae45b14de14e65e89c89680914afba446f6c8d7fc3"

      def install
        bin.install stable.url.split("/")[-1] => "ytt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.47.0/ytt-linux-arm64"
      sha256 "af2e92fafd603ed0e19d4a04c7c375f895bddee9e11720cef980498a49127a17"

      def install
        bin.install stable.url.split("/")[-1] => "ytt"
      end
    end
  end
end
