# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YttExt < Formula
  desc ""
  homepage ""
  version "0.48.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-darwin-arm64.tar.gz"
      sha256 "fae19e38ba37f98517b08ff5722a943e40624a2ceb9962a484833cb3eedd86a9"

      def install
        bin.install stable.url.split("/")[-1].split(".")[0] => "ytt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-darwin-amd64.tar.gz"
      sha256 "f82336a7bf854c551cd6fd6775051dc74f5e99acd93240c88d00520cc376fff0"

      def install
        bin.install stable.url.split("/")[-1].split(".")[0] => "ytt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-linux-arm64.tar.gz"
      sha256 "93b11698b53aaf9c6e42acd3f57592913ffb6d14aea27b01368377cbdbdf2963"

      def install
        bin.install stable.url.split("/")[-1].split(".")[0] => "ytt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marxus/ytt-ext/releases/download/v0.48.0/ytt-linux-amd64.tar.gz"
      sha256 "44fb1dc16446add1f14543a42f7b3e366a598cf10f718475d35bb12bf3288c30"

      def install
        bin.install stable.url.split("/")[-1].split(".")[0] => "ytt"
      end
    end
  end
end
