name: goreleaser

"on": { push: { tags: ["*"] } }

permissions: { contents: write }

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: "Setup Go"
        uses: actions/setup-go@v4
      - name: "Fix Homebrew"
        run: "cat <<<\"$(cat .goreleaser.yaml | env TAG=${{ github.ref_name }} envsubst '$TAG')\" >.goreleaser.yaml"
      - name: "Run GoReleaser"
        uses: goreleaser/goreleaser-action@v5
        env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        with:
          distribution: goreleaser
          version: latest
          args: "release --clean --skip=validate"
